package com.example.focus_shield_android

data class FocusShieldProtectionStatus(
    val nativeStatusVersion: Int,
    val protectionMode: String,
    val vpnActive: Boolean,
    val blocklistLoaded: Boolean,
    val blockedDomainCount: Int,
    val nativeDnsReady: Boolean,
    val nativeLoadedDomainCount: Int,
    val packetLoopPrepared: Boolean,
    val packetLoopRunning: Boolean,
    val packetsObserved: Long,
    val ipPacketsObserved: Long,
    val ipv6PacketsObserved: Long,
    val udpPacketsObserved: Long,
    val ipv6UdpPacketsObserved: Long,
    val tcpPacketsObserved: Long,
    val ipv6TcpPacketsObserved: Long,
    val dnsCandidatePacketsObserved: Long,
    val ipv6DnsCandidatePacketsObserved: Long,
    val dnsParseAttempts: Long,
    val dnsParseFailures: Long,
    val lastPacketProtocol: String,
    val lastParserError: String,
    val lastPacketSummary: String,
    val dnsParserPrepared: Boolean,
    val dnsQueriesParsed: Long,
    val lastParsedHostname: String,
    val dryRunModeReady: Boolean,
    val dryRunBlocksDetected: Long,
    val lastDryRunDecision: String,
    val dnsProxyPrepared: Boolean,
    val dnsProxyRunning: Boolean,
    val dnsProxyMode: String,
    val dnsProxyQueriesReceived: Long,
    val dnsProxyQueriesForwarded: Long,
    val dnsProxyResponsesReturned: Long,
    val dnsProxyErrors: Long,
    val lastDnsProxyHost: String,
    val lastDnsProxyDecision: String,
    val lastDnsProxyError: String,
    val liveTrafficReadEnabled: Boolean,
    val blockingEnabled: Boolean,
    val liveObservationToggleAvailable: Boolean,
    val liveObservationRequested: Boolean,
    val liveObservationGateVersion: Int,
    val liveObservationCodeGateReady: Boolean,
    val liveObservationCodeGateUnlocked: Boolean,
    val liveObservationSafetyGate: String,
    val liveObservationUnlockAttempts: Int,
    val statusMessage: String,
    val blocklistError: String
) {
    fun toMap(): Map<String, Any> {
        return mapOf(
            "nativeStatusVersion" to nativeStatusVersion,
            "protectionMode" to protectionMode,
            "vpnActive" to vpnActive,
            "blocklistLoaded" to blocklistLoaded,
            "blockedDomainCount" to blockedDomainCount,
            "nativeDnsReady" to nativeDnsReady,
            "nativeLoadedDomainCount" to nativeLoadedDomainCount,
            "packetLoopPrepared" to packetLoopPrepared,
            "packetLoopRunning" to packetLoopRunning,
            "packetsObserved" to packetsObserved,
            "ipPacketsObserved" to ipPacketsObserved,
            "ipv6PacketsObserved" to ipv6PacketsObserved,
            "udpPacketsObserved" to udpPacketsObserved,
            "ipv6UdpPacketsObserved" to ipv6UdpPacketsObserved,
            "tcpPacketsObserved" to tcpPacketsObserved,
            "ipv6TcpPacketsObserved" to ipv6TcpPacketsObserved,
            "dnsCandidatePacketsObserved" to dnsCandidatePacketsObserved,
            "ipv6DnsCandidatePacketsObserved" to ipv6DnsCandidatePacketsObserved,
            "dnsParseAttempts" to dnsParseAttempts,
            "dnsParseFailures" to dnsParseFailures,
            "lastPacketProtocol" to lastPacketProtocol,
            "lastParserError" to lastParserError,
            "lastPacketSummary" to lastPacketSummary,
            "dnsParserPrepared" to dnsParserPrepared,
            "dnsQueriesParsed" to dnsQueriesParsed,
            "lastParsedHostname" to lastParsedHostname,
            "dryRunModeReady" to dryRunModeReady,
            "dryRunBlocksDetected" to dryRunBlocksDetected,
            "lastDryRunDecision" to lastDryRunDecision,
            "dnsProxyPrepared" to dnsProxyPrepared,
            "dnsProxyRunning" to dnsProxyRunning,
            "dnsProxyMode" to dnsProxyMode,
            "dnsProxyQueriesReceived" to dnsProxyQueriesReceived,
            "dnsProxyQueriesForwarded" to dnsProxyQueriesForwarded,
            "dnsProxyResponsesReturned" to dnsProxyResponsesReturned,
            "dnsProxyErrors" to dnsProxyErrors,
            "lastDnsProxyHost" to lastDnsProxyHost,
            "lastDnsProxyDecision" to lastDnsProxyDecision,
            "lastDnsProxyError" to lastDnsProxyError,
            "liveTrafficReadEnabled" to liveTrafficReadEnabled,
            "blockingEnabled" to blockingEnabled,
            "liveObservationToggleAvailable" to liveObservationToggleAvailable,
            "liveObservationRequested" to liveObservationRequested,
            "liveObservationGateVersion" to liveObservationGateVersion,
            "liveObservationCodeGateReady" to liveObservationCodeGateReady,
            "liveObservationCodeGateUnlocked" to liveObservationCodeGateUnlocked,
            "liveObservationSafetyGate" to liveObservationSafetyGate,
            "liveObservationUnlockAttempts" to liveObservationUnlockAttempts,
            "statusMessage" to statusMessage,
            "blocklistError" to blocklistError
        )
    }

    companion object {
        const val CURRENT_VERSION = 6

        fun build(blocklistStatus: FocusShieldBlocklistStatus): FocusShieldProtectionStatus {
            val dnsProxyStatus = FocusShieldDnsProxy.snapshot()

            return FocusShieldProtectionStatus(
                nativeStatusVersion = CURRENT_VERSION,
                protectionMode = FocusShieldVpnService.protectionMode,
                vpnActive = FocusShieldVpnService.isRunning,
                blocklistLoaded = blocklistStatus.loaded,
                blockedDomainCount = blocklistStatus.count,
                nativeDnsReady = FocusShieldVpnService.dnsFilteringReady,
                nativeLoadedDomainCount = FocusShieldVpnService.nativeBlockedDomainCount,
                packetLoopPrepared = FocusShieldVpnService.packetLoopPrepared,
                packetLoopRunning = FocusShieldVpnService.packetLoopRunning,
                packetsObserved = FocusShieldVpnService.packetsObserved,
                ipPacketsObserved = FocusShieldVpnService.ipPacketsObserved,
                ipv6PacketsObserved = FocusShieldVpnService.ipv6PacketsObserved,
                udpPacketsObserved = FocusShieldVpnService.udpPacketsObserved,
                ipv6UdpPacketsObserved = FocusShieldVpnService.ipv6UdpPacketsObserved,
                tcpPacketsObserved = FocusShieldVpnService.tcpPacketsObserved,
                ipv6TcpPacketsObserved = FocusShieldVpnService.ipv6TcpPacketsObserved,
                dnsCandidatePacketsObserved =
                    FocusShieldVpnService.dnsCandidatePacketsObserved,
                ipv6DnsCandidatePacketsObserved =
                    FocusShieldVpnService.ipv6DnsCandidatePacketsObserved,
                dnsParseAttempts = FocusShieldVpnService.dnsParseAttempts,
                dnsParseFailures = FocusShieldVpnService.dnsParseFailures,
                lastPacketProtocol = FocusShieldVpnService.lastPacketProtocol,
                lastParserError = FocusShieldVpnService.lastParserError,
                lastPacketSummary = FocusShieldVpnService.lastPacketSummary,
                dnsParserPrepared = FocusShieldVpnService.dnsParserPrepared,
                dnsQueriesParsed = FocusShieldVpnService.dnsQueriesParsed,
                lastParsedHostname = FocusShieldVpnService.lastParsedHostname,
                dryRunModeReady = FocusShieldVpnService.dryRunModeReady,
                dryRunBlocksDetected = FocusShieldVpnService.dryRunBlocksDetected,
                lastDryRunDecision = FocusShieldVpnService.lastDryRunDecision,
                dnsProxyPrepared = dnsProxyStatus.dnsProxyPrepared,
                dnsProxyRunning = dnsProxyStatus.dnsProxyRunning,
                dnsProxyMode = dnsProxyStatus.dnsProxyMode,
                dnsProxyQueriesReceived = dnsProxyStatus.dnsProxyQueriesReceived,
                dnsProxyQueriesForwarded = dnsProxyStatus.dnsProxyQueriesForwarded,
                dnsProxyResponsesReturned = dnsProxyStatus.dnsProxyResponsesReturned,
                dnsProxyErrors = dnsProxyStatus.dnsProxyErrors,
                lastDnsProxyHost = dnsProxyStatus.lastDnsProxyHost,
                lastDnsProxyDecision = dnsProxyStatus.lastDnsProxyDecision,
                lastDnsProxyError = dnsProxyStatus.lastDnsProxyError,
                liveTrafficReadEnabled = FocusShieldVpnService.liveTrafficReadEnabled,
                blockingEnabled = FocusShieldVpnService.blockingEnabled,
                liveObservationToggleAvailable =
                    FocusShieldVpnService.liveObservationToggleAvailable,
                liveObservationRequested = FocusShieldVpnService.liveObservationRequested,
                liveObservationGateVersion = FocusShieldVpnService.liveObservationGateVersion,
                liveObservationCodeGateReady =
                    FocusShieldVpnService.liveObservationCodeGateReady,
                liveObservationCodeGateUnlocked =
                    FocusShieldVpnService.liveObservationCodeGateUnlocked,
                liveObservationSafetyGate = FocusShieldVpnService.liveObservationSafetyGate,
                liveObservationUnlockAttempts =
                    FocusShieldVpnService.liveObservationUnlockAttempts,
                statusMessage = FocusShieldVpnService.statusMessage,
                blocklistError = blocklistStatus.error ?: ""
            )
        }
    }
}
